"""Sprint 2: Ajout table CarteCCE

Revision ID: 1788df7a2ba8
Revises: 423e8d4c1c8c
Create Date: 2026-02-06 13:33:02.435351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1788df7a2ba8'
down_revision: Union[str, None] = '423e8d4c1c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
