"""Création table Client (test setup)

Revision ID: 423e8d4c1c8c
Revises: 
Create Date: 2026-02-06 12:01:36.114017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423e8d4c1c8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client',
    sa.Column('id_client_cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('num_tel_tel', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_client_cid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Client')
    # ### end Alembic commands ###
